BLUEZ_NAMESPACE = "/org/bluez/"
ADAPTER_NAME = "hci0"
BLUEZ_SERVICE_NAME = "org.bluez"
ADVERTISING_MANAGER_INTERFACE = "org.bluez.LEAdvertisingManager1"
ADVERTISEMENT_INTERFACE = "org.bluez.LEAdvertisement1"
GATT_MANAGER_INTERFACE = "org.bluez.GattManager1"
GATT_SERVICE_INTERFACE = "org.bluez.GattService1"
GATT_CHARACTERISTIC_INTERFACE = "org.bluez.GattCharacteristic1"
DEVICE_INTERFACE = "org.bluez.Device1"
DBUS_PROPERTIES = "org.freedesktop.DBus.Properties"
DBUS_OM_IFACE = "org.freedesktop.DBus.ObjectManager"
TEMPERATURE_SVC_UUID = "12345678-1234-5678-1234-56789abcdef0"  # Example UUID for a GATT service
TEMPERATURE_CHR_UUID = "12345678-1234-5678-1234-56789abcdef1"  # Example UUID for a GATT characteristic
